---
title: "filter_join.Rmd"
author: "Jonah Merriam"
date: "8/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries}
library(tidyverse)
library(readxl)
library(here) 
library(kableExtra)
```

```{r Data}
fish<-read_csv(here("data","fish.csv"))
kelp_abur<-read_excel(here("data","kelp.xlsx"), sheet="abur")

```

```{r Filtering}
fish_garibaldi <- fish %>% filter(common_name == "garibaldi")

##The == tells R to find only exact matches in the row of common_name and then these are used to form the new table based on the characters given

fish_over50 <- fish %>% filter(total_count >= 50)

##The exclusion can be based on numeric columns too if you give R instructions to exclude using equals and greater than or less to signs
```

```{r Or/And}
fish_3sp <- fish %>% filter(common_name == "garibaldi" | common_name == "blacksmith" |  common_name == "black surfperch")

##The vertical line notates an Or statement to R so any fish with this name in the common_name column will appear on this table

aque_2018 <- fish %>% filter(year == 2018, site == "aque")

##A comma or an & between the two specifications will read into R as an and statement which requires both criteria to be met to be included
```

```{r Partial Strings}
fish_bl <- fish %>% filter(str_detect(common_name, pattern = "black"))

##Fish with a common name containing the word black are put into this graph using the filter()+str_detect() functions combined 

##We can also exclude observations that contain a set string pattern by adding the negate = TRUE argument within str_detect() 
```

```{r Joining}
abur_kelp_fish <- kelp_abur %>% full_join(fish, by = c("year", "site")) 

##Full join will keep all of the data and add the variables you tell it together while keeping the other variables in different rows and filling in N/A for any value left blank. This is the safest way to merge data frames because nothing is lost.

kelp_fish_left <- kelp_abur %>% left_join(fish, by = c("year","site"))

##Left join will only keep the observations in data frame b(fish) that match the observations for data frame a(abur) 

kelp_fish_injoin <- kelp_abur %>% inner_join(fish, by = c("year", "site"))

##Innerjoin only keeps the observations that are shared between both of the data frames 
```

```{r kable}
kable(my_fish_join)

##This will make a normal html table when knitted

my_fish_join %>% kable() %>% kable_styling(bootstrap_options = "striped", full_width = FALSE)

##This will make a nicer table
```




