---
title: "ggplot.practice.Rmd"
author: "Jonah Merriam"
date: "8/4/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r prep}
##Download and prep these libraries first
library(tidyverse)
library(readxl)
library(here)
##here function tells R where to look for a file
ca_np<-read_csv(here("data","ca_np.csv"))
##Left of arrow is the new name of the file if R finds it successfully (check the global environment for it)
##To observe the data look at functions like summary(), names(), and head() to get a better idea of the data structure 
ci_np<- read_excel(here("data","ci_np.xlsx"))
```

```{r Basic Plots}
library(ggplot2)
##ggplot(data = df_name, aes(x = x_var_name, y = y_var_name)) + 
##geom_type()
##This is the basic outline of a ggplot graph which requires a set of data, x &y variables, and the type of graph is determined by the geom_type

ggplot(data = ci_np, aes(x = year, y = visitors)) +
  geom_line()

##These plots can be saved under simpler names so they're easier to pull up

gg_base<-ggplot(data = ci_np, aes(x = year, y = visitors)) +
  geom_line()

##geom_* can be changed to produce different kinds of plots like bar graphs (col) point graphs (point) line graphs (line) ect

```

```{r Graph Aesthetics}
##color = or colour =: update point or line colors, fill =: update fill color for objects with areas, linetype =: update the line type (dashed, long dash, etc.), pch =: update the point style, size =: update the element size (e.g. of points or line thickness), alpha =: update element opacity (1 = opaque, 0 = transparent)

gg_base +
  geom_line(
    color = "purple",
    linetype = "dashed"
  )
##Changes line color and type

gg_base + 
  geom_point(color = "purple",
             pch = 17,
             size = 4,
             alpha = 0.5)
##Here is a costum example of a graph of the data
ggplot(data = ci_np, aes(x = year, y = visitors)) +
geom_point(color= "green", pch=3, size=4, alpha=0.7)
##Here is another example of visual changes to the graph's aesthetics  

##Aesthetics can be customized to change with different variables. This is done by the function aes() and those variables are found within () and within the geom_* function's () aswell 
ggplot(data = ci_np, aes(x = year, y = visitors)) +     geom_point(aes(size=visitors, color=visitors), alpha = 0.5)

##The fill() function can be used in the geom_*() function to color the differences in the variables into the plot based on a color spectrum
ggplot(data = ci_np, aes(x = year, y = visitors)) + 
  geom_col(aes(fill = visitors))
```

```{r ggplot themes}
##Themes can be added on after the geom_* function is closed to give the graph a theme() 
ggplot(data = ci_np, aes(x = year, y = visitors)) + geom_point(aes(size=visitors,color=visitors),alpha=0.5)+ theme_minimal()

```

```{r ggplot labels}
##labels (title, subtitle, x & y) can be added by including the labs() function 

ggplot(data = ci_np, aes(x = year, y = visitors)) + geom_point(aes(size=visitors,color=visitors),alpha=0.5)+ theme_bw()+ labs(x="Year", y="Annual Park Visitors", title="Channel Islands NP Visitation", subtitle = "(1963-2016)")

##axis formating and range can be changed using the scales() package but not exactly sure how
```

```{r ggplot w/ multiple series}
##If the data needs to be broken into different groups like different national parks in this case then the group= in the aes() function will separate out the different groups in that collumn 
ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name)) + geom_line()

```

```{r Faceting Graphs}
gg_np+ geom_line(show.legend = FALSE)+ theme_light()+ labs(x="Year",y="annual Visitors")+ facet_wrap(~park_name)
##facet_wrap() function splits the data up into separate graphs based on the variable you give it
```

```{r GGsave}
ggsave(here("figures", "np_graph.jpg"), dpi = 180, width = 8, height = 7)
##To save/download a plot use ggsave and tell it where to go and what to call it
```

