---
title: "JSM.fisheries.Rmd"
author: "Jonah Merriam"
date: "8/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Libraries}
library(tidyverse)
library(here)  
library(janitor) 
library(paletteer)
```

```{r Data Readin}
us_landings <- read_csv(here("data","noaa_landings.csv"), na = "no data")

##The na="no data" changes any label that has no data to na
```

```{r Cleaning}
##The goal of cleaning the data set is to make the data more code friendly. This will include steps like normalizing the column names in janitor, making the words all lower case, removing the dollar sign in the price column and in this case only selecting for salmon as the exercise suggests.

salmon_clean <- us_landings %>%          clean_names() %>% # Make column headers snake_case
  mutate(
    afs_name = str_to_lower(afs_name)
  ) %>% # Converts character columns to lowercase
  mutate(dollars_num = parse_number(dollars_usd)) %>% # Just keep numbers from $ column
  filter(str_detect(afs_name, pattern = "salmon")) %>% # Only keep entries w/"salmon"
  separate(afs_name, into = c("group", "subgroup"), sep = ", ") %>% # Note comma-space
  drop_na(dollars_num) # Drop (listwise deletion) any observations with NA for dollars_num
```

```{r Summarize}
salmon_us_annual <- salmon_clean %>% 
  group_by(year, subgroup) %>% 
  summarize(
    tot_value = sum(dollars_num, na.rm = TRUE),
  )

##Allows the year subgroup and total dollar value to be seen in a table together 
```

```{r Plot}
salmon.gg<-ggplot(salmon_us_annual, aes(x=year, y=tot_value, group= subgroup))+ geom_line(aes(color=subgroup))+theme_bw()+labs(x="Year", y="US commercial salmon value (USD)")+  scale_color_paletteer_d("awtools::bpalette")
salmon.gg
```




